services:
  backend:
    build:
      context: ../backend # actual project code
      dockerfile: ../docker/Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
